require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CoordinatorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Coordinator. As you add validations to Coordinator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      HCName: 'Jack Daniels',
      HCPhone: '3334445555',
      HCEmail: 'clapyourhands@doctor.edu'
    }
  }

  let(:invalid_attributes) {
    {
        HCName: nil,
        HCPhone: '3334445555',
        HCEmail: 'clapyourhands@doctor.edu'
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CoordinatorsController. Be sure to keep this updated too.
  let(:valid_session) { {
      user_id: 1,
      user_role: 'admin'
  } }
  describe "GET #index" do
    it "returns a success response" do
      coordinator = Coordinator.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      coordinator = Coordinator.create! valid_attributes
      get :show, params: {id: coordinator.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      coordinator = Coordinator.create! valid_attributes
      get :edit, params: {id: coordinator.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Coordinator" do
        expect {
          post :create, params: {coordinator: valid_attributes}, session: valid_session
        }.to change(Coordinator, :count).by(1)
      end

      it "redirects to the created coordinator" do
        post :create, params: {coordinator: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Coordinator.last)
      end
    end

    context "with invalid params" do
      it "returns a failure response and displays 'new' template" do
        post :create, params: {coordinator: invalid_attributes}, session: valid_session
        expect(response).to render_template(:new)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {
            HCName: 'Jack Daniels',
            HCPhone: '3334445555',
            HCEmail: 'clapyourhands@doctor.edu'
        }
      }

      it "updates the requested coordinator" do
        coordinator = Coordinator.create! valid_attributes
        put :update, params: {id: coordinator.to_param, coordinator: new_attributes}, session: valid_session
        coordinator.reload
        expect(controller.notice).to eq('Coordinator was successfully updated.')
      end

      it "redirects to the coordinator" do
        coordinator = Coordinator.create! valid_attributes
        put :update, params: {id: coordinator.to_param, coordinator: new_attributes}, session: valid_session
        expect(response).to redirect_to(coordinator)
      end
    end

    context "with invalid params" do
      it "returns a failure response and displays :edit template" do
        coordinator = Coordinator.create! valid_attributes
        put :update, params: {id: coordinator.to_param, coordinator: invalid_attributes}, session: valid_session
        expect(response).to render_template(:edit)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested coordinator" do
      coordinator = Coordinator.create! valid_attributes
      expect {
        delete :destroy, params: {id: coordinator.to_param}, session: valid_session
      }.to change(Coordinator, :count).by(-1)
    end

    it "redirects to the coordinators list" do
      coordinator = Coordinator.create! valid_attributes
      delete :destroy, params: {id: coordinator.to_param}, session: valid_session
      expect(response).to redirect_to(coordinators_url)
    end
  end

end
